/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArcTestnetDegenNFT } from "./ArcTestnetDegenNFT";
export type { NFTCollection } from "./NFTCollection";
export type { NFTFactory } from "./NFTFactory";
